name: Release GitHub Action
description: Create a semantic release for your Github Action.
author: bubkoo <bubkoo.wy@gmail.com>
inputs:
  cwd:
    required: false
    description: Specify another working directory for semantic release. Default one is provided by github.
  dry_run:
    required: false
    description: Whether to run semantic release in `dry-run` mode. It will override the dryRun attribute in your configuration file.
  branches:
    required: false
    description: The branches on which releases should happen. It will override the branches attribute in your configuration file. Support for semantic-release above v16. See https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches for more information.
  commit_analyzer:
    required: false
    description: Options for semantic-release/commit-analyzer.
  release_notes_generator:
    required: false
    description: Options for semantic-release/release-notes-generator.
  changelog:
    required: false
    description: Options for semantic-release/changelog.
  github:
    required: false
    description: Options for semantic-release/github.
  git:
    required: false
    description: Options for semantic-release/git.

outputs:
  last_release_version:
    description: Version of the previous release, if there was one.
  last_release_git_head:
    description: The sha of the last commit being part of the last release, if there was one.
  last_release_git_tag:
    description: The Git tag associated with the last release, if there was one.
  new_release_published:
    description: Whether a new release was published.
  new_release_version:
    description: Version of the new release.
  new_release_major_version:
    description: Major version of the new release.
  new_release_minor_version:
    description: Minor version of the new release.
  new_release_patch_version:
    description: Patch version of the new release.
  new_release_channel:
    description: The distribution channel on which the last release was initially made available (undefined for the default distribution channel).
  new_release_notes:
    description: The release notes for the new release.
  new_release_git_head:
    description: The sha of the last commit being part of the new release.
  new_release_git_tag:
    description: The Git tag associated with the new release.

runs:
  using: node20
  main: dist/index.js
branding:
  icon: truck
  color: blue
